version: '3.8'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8032:8000
        volumes:
            - .:/app
networks:
    default:
        name: tele2corp