# Generated by Django 3.1.3 on 2021-04-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Environment Data',
                'verbose_name_plural': 'Environment Data',
            },
        ),
        migrations.AddConstraint(
            model_name='environmentdata',
            constraint=models.UniqueConstraint(fields=('Name', 'Value'), name='unique oachfrontendenvironmentdata'),
        ),
    ]
