# Generated by Django 3.1.3 on 2021-04-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100, verbose_name='LDAP Server')),
                ('port', models.CharField(max_length=100, verbose_name='LDAP Port')),
                ('base_dn', models.CharField(max_length=100, verbose_name='Base DN')),
                ('search_field', models.CharField(max_length=100, verbose_name='Search Field')),
                ('ldap_acc', models.CharField(max_length=100, verbose_name='Service Account')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'LDAP Configuration',
                'verbose_name_plural': 'LDAP Configuration',
            },
        ),
    ]
