# Generated by Django 3.1.3 on 2021-04-15 20:18

import django.core.validators
from django.db import migrations, models
import singleview_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=50)),
                ('AccountSSN', models.CharField(max_length=50)),
                ('AccountName', models.CharField(max_length=255)),
                ('AccountClass', models.CharField(max_length=30)),
                ('AccountType', models.CharField(max_length=30)),
                ('AccountSubType', models.CharField(max_length=30)),
                ('AccountCreditLimit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('ParentAccountId', models.CharField(blank=True, max_length=15, null=True)),
                ('RootAccountId', models.CharField(blank=True, max_length=15, null=True)),
                ('AccountEmailAddress', models.EmailField(max_length=100)),
                ('AccountDateOfBirth', models.DateField(validators=[singleview_api.models.date_age_validator])),
                ('AccountAddress', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityAccountId', models.CharField(max_length=15)),
                ('ActivityOrderId', models.CharField(blank=True, max_length=15, null=True)),
                ('ActivityAssetId', models.CharField(blank=True, max_length=15, null=True)),
                ('ActivitySRId', models.CharField(blank=True, max_length=15, null=True)),
                ('ActivityInvoiceId', models.CharField(blank=True, max_length=15, null=True)),
                ('ActivityType', models.CharField(max_length=30)),
                ('ActivityCategory', models.CharField(max_length=30)),
                ('ActivityStatus', models.CharField(max_length=30)),
                ('ActivityOwner', models.CharField(max_length=100)),
                ('ActivityDepartment', models.CharField(max_length=30)),
                ('ActivityComment', models.TextField()),
                ('ActivityDescription', models.TextField(blank=True, null=True)),
                ('ActivitySLT', models.DateField(validators=[singleview_api.models.date_slt_validator])),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceAccountId', models.CharField(max_length=15)),
                ('InvoiceNumber', models.CharField(max_length=15)),
                ('InvoiceType', models.CharField(max_length=30)),
                ('InvoiceStatus', models.CharField(max_length=30)),
                ('InvoiceAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('InvoiceDate', models.DateField()),
                ('InvoiceURL', models.URLField()),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentAccountId', models.CharField(max_length=15)),
                ('PaymentInvoiceId', models.CharField(max_length=15)),
                ('PaymentMemoNumber', models.CharField(max_length=15)),
                ('PaymentType', models.CharField(max_length=30)),
                ('PaymentStatus', models.CharField(max_length=30)),
                ('PaymentAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentDate', models.DateField()),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceRequestAccountId', models.CharField(max_length=15)),
                ('ServiceRequestOrderId', models.CharField(blank=True, max_length=15, null=True)),
                ('ServiceRequestAssetId', models.CharField(blank=True, max_length=15, null=True)),
                ('ServiceRequestInvoiceId', models.CharField(blank=True, max_length=15, null=True)),
                ('ServiceRequestProduct', models.CharField(blank=True, max_length=30, null=True)),
                ('ServiceRequestType', models.CharField(blank=True, max_length=30, null=True)),
                ('ServiceRequestArea', models.CharField(blank=True, max_length=30, null=True)),
                ('ServiceRequestSubArea', models.CharField(blank=True, max_length=30, null=True)),
                ('ServiceRequestResolutionCode', models.CharField(blank=True, max_length=30, null=True)),
                ('ServiceRequestCaseLevel1', models.CharField(blank=True, max_length=30, null=True)),
                ('ServiceRequestCaseLevel2', models.CharField(blank=True, max_length=30, null=True)),
                ('ServiceRequestCaseLevel3', models.CharField(blank=True, max_length=30, null=True)),
                ('ServiceRequestStatus', models.CharField(max_length=30)),
                ('ServiceRequestOwner', models.CharField(max_length=100)),
                ('ServiceRequestDepartment', models.CharField(max_length=30)),
                ('ServiceRequestComment', models.TextField(blank=True, null=True)),
                ('ServiceRequestSLT', models.DateField(validators=[singleview_api.models.date_slt_validator])),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TreatmentAccountId', models.CharField(max_length=15)),
                ('TreatmentStage', models.CharField(max_length=30)),
                ('TreatmentStatus', models.CharField(max_length=30)),
                ('TreatmentOpenDate', models.DateField()),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
            },
        ),
    ]
