# Generated by Django 3.1.3 on 2021-04-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleview_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='PaymentMemoNumber',
            field=models.CharField(max_length=50),
        ),
    ]
