# Generated by Django 3.1.3 on 2021-04-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleview_api', '0002_auto_20210418_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='AccountMobile',
            field=models.EmailField(default='+37120750174', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='AccountStanding',
            field=models.EmailField(default='Good Standing', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='AccountStatus',
            field=models.EmailField(default='Active', max_length=30),
            preserve_default=False,
        ),
    ]
