# Generated by Django 3.1.3 on 2021-04-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleview_api', '0003_auto_20210425_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='DisputeExpiryDate',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='DisputeOpenDate',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='DueAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='DueDate',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='InvoiceAccountNumber',
            field=models.CharField(default='10001', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='InvoiceVatAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='InvoiceVatExclAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
