# Generated by Django 3.1.3 on 2021-04-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleview_api', '0004_auto_20210426_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='DisputeExpiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='DisputeOpenDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
