version: '3.8'
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8050:8000
        volumes:
            - .:/app
networks:
    default:
        name: tele2corp