version: '3.8'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8036:8000
        volumes:
            - .:/app
    redis:
        image: 'redis:alpine'
networks:
    default:
        name: tele2corp