version: '3.8'
services:
    sv_api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8010:8000
        volumes:
            - .:/app
        depends_on: 
            - sv_db
    sv_db:
        image: mysql/mysql-server
        restart: always
        environment:
            MYSQL_DATABASE: sv_db
            MYSQL_ROOT_PASSWORD: Tele2SVdbPa##w0rd
        ports:
            - "33066:3306"
networks:
    default:
        name: tele2corp