# Generated by Django 3.1.3 on 2021-04-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oach_service_requests_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Service Requests API Transaction', 'verbose_name_plural': 'Service Requests API Transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactionparameter',
            options={'verbose_name': 'Service Requests API Parameter', 'verbose_name_plural': 'Service Requests API Parameters'},
        ),
    ]
