# Generated by Django 3.1.3 on 2021-04-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetOrderId', models.CharField(max_length=15)),
                ('AssetOrderItemId', models.CharField(max_length=15)),
                ('CustomerAccountId', models.CharField(max_length=15)),
                ('BillingAccountId', models.CharField(max_length=15)),
                ('ParentAssetId', models.CharField(blank=True, max_length=15, null=True)),
                ('RootAssetId', models.CharField(max_length=15)),
                ('Product', models.CharField(max_length=50)),
                ('PrimaryAttributeName', models.CharField(blank=True, max_length=30, null=True)),
                ('PrimaryAttributeValue', models.CharField(blank=True, max_length=30, null=True)),
                ('Status', models.CharField(max_length=30)),
                ('ErrorMessage', models.CharField(blank=True, max_length=255, null=True)),
                ('ActualStartDate', models.DateField()),
                ('ContractStartDate', models.DateField(blank=True, null=True)),
                ('ContractEndDate', models.DateField(blank=True, null=True)),
                ('RegretEndDate', models.DateField(blank=True, null=True)),
                ('PlannedDisconnectDate', models.DateField(blank=True, null=True)),
                ('ActualEndDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Installed Asset',
                'verbose_name_plural': 'Installed Assets',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExternalOrderNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('OrderNumber', models.CharField(max_length=15)),
                ('CustomerAccountId', models.CharField(max_length=15)),
                ('BillingAccountId', models.CharField(max_length=15)),
                ('Type', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
                ('Source', models.CharField(max_length=30)),
                ('SalesPartner', models.CharField(blank=True, max_length=100, null=True)),
                ('ErrorMessage', models.CharField(blank=True, max_length=255, null=True)),
                ('OrderDate', models.DateField()),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderItemOrderId', models.CharField(max_length=15)),
                ('CustomerAccountId', models.CharField(max_length=15)),
                ('BillingAccountId', models.CharField(max_length=15)),
                ('ParentOrderItemId', models.CharField(blank=True, max_length=15, null=True)),
                ('RootOrderItemId', models.CharField(max_length=15)),
                ('Product', models.CharField(max_length=50)),
                ('PrimaryAttributeName', models.CharField(blank=True, max_length=30, null=True)),
                ('PrimaryAttributeValue', models.CharField(blank=True, max_length=30, null=True)),
                ('Status', models.CharField(max_length=30)),
                ('SubStatus', models.CharField(max_length=30)),
                ('Action', models.CharField(blank=True, max_length=30, null=True)),
                ('ErrorMessage', models.CharField(blank=True, max_length=255, null=True)),
                ('StatusDate', models.DateField()),
                ('ContractStartDate', models.DateField(blank=True, null=True)),
                ('ContractEndDate', models.DateField(blank=True, null=True)),
                ('RegretEndDate', models.DateField(blank=True, null=True)),
                ('PlannedDisconnectDate', models.DateField(blank=True, null=True)),
                ('DisconnectDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
