# Generated by Django 3.1.3 on 2021-04-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedelivery_api', '0002_installedasset_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedasset',
            name='BillingAccountNumber',
            field=models.CharField(default='1000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='BillingAccountNumber',
            field=models.CharField(default='1000', max_length=15),
            preserve_default=False,
        ),
    ]
