# Generated by Django 3.1.3 on 2021-04-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedelivery_api', '0003_auto_20210425_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedasset',
            name='CustomerAccountNumber',
            field=models.CharField(default='100001', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='BillingAccountNumber',
            field=models.CharField(default='100002', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='CustomerAccountNumber',
            field=models.CharField(default='100001', max_length=15),
            preserve_default=False,
        ),
    ]
